#!/bin/bash

mkdir /opt
mkdir /opt/hawkbit

if [ -z "$DOCKER_TAG" ];
 then
  echo "downloading hawkBit release $DOCKER_TAG" 
  curl -f -o /opt/hawkbit/hawkbit-example-app.jar -L https://repo.eclipse.org/service/local/artifact/maven/redirect?r=hawkbit-releases&g=org.eclipse.hawkbit&a=hawkbit-example-app&v=$DOCKER_TAG
 ;
 else 
   echo "downloading hawkBit snapshot"
   curl -f -o /opt/hawkbit/hawkbit-example-app.jar -L 'https://repo.eclipse.org/service/local/artifact/maven/redirect?r=hawkbit-snapshots&g=org.eclipse.hawkbit&a=hawkbit-example-app&v=LATEST'
 ;
fi